// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package dbgen

import (
	"context"
	"time"
)

const claimParcel = `-- name: ClaimParcel :exec
INSERT INTO parcel_claims (session_id, player_id, parcel_id, kg_code, gnr, area_sqm, landuse, purchase_price)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type ClaimParcelParams struct {
	SessionID     string  `json:"session_id"`
	PlayerID      string  `json:"player_id"`
	ParcelID      string  `json:"parcel_id"`
	KgCode        string  `json:"kg_code"`
	Gnr           string  `json:"gnr"`
	AreaSqm       float64 `json:"area_sqm"`
	Landuse       *string `json:"landuse"`
	PurchasePrice int64   `json:"purchase_price"`
}

func (q *Queries) ClaimParcel(ctx context.Context, arg ClaimParcelParams) error {
	_, err := q.db.ExecContext(ctx, claimParcel,
		arg.SessionID,
		arg.PlayerID,
		arg.ParcelID,
		arg.KgCode,
		arg.Gnr,
		arg.AreaSqm,
		arg.Landuse,
		arg.PurchasePrice,
	)
	return err
}

const claimTreasure = `-- name: ClaimTreasure :exec
UPDATE treasures SET found_by = ?, found_at = CURRENT_TIMESTAMP WHERE id = ? AND found_by IS NULL
`

type ClaimTreasureParams struct {
	FoundBy *string `json:"found_by"`
	ID      int64   `json:"id"`
}

func (q *Queries) ClaimTreasure(ctx context.Context, arg ClaimTreasureParams) error {
	_, err := q.db.ExecContext(ctx, claimTreasure, arg.FoundBy, arg.ID)
	return err
}

const completeChallenge = `-- name: CompleteChallenge :exec
UPDATE challenges SET completed = 1, completed_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) CompleteChallenge(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeChallenge, id)
	return err
}

const convertParcel = `-- name: ConvertParcel :exec
UPDATE parcel_claims SET converted_to = ? WHERE id = ?
`

type ConvertParcelParams struct {
	ConvertedTo *string `json:"converted_to"`
	ID          int64   `json:"id"`
}

func (q *Queries) ConvertParcel(ctx context.Context, arg ConvertParcelParams) error {
	_, err := q.db.ExecContext(ctx, convertParcel, arg.ConvertedTo, arg.ID)
	return err
}

const createChallenge = `-- name: CreateChallenge :exec
INSERT INTO challenges (session_id, player_id, challenge_type, title, description, target_parcel_id, reward_coins, reward_xp)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateChallengeParams struct {
	SessionID      string  `json:"session_id"`
	PlayerID       string  `json:"player_id"`
	ChallengeType  string  `json:"challenge_type"`
	Title          string  `json:"title"`
	Description    *string `json:"description"`
	TargetParcelID *string `json:"target_parcel_id"`
	RewardCoins    int64   `json:"reward_coins"`
	RewardXp       int64   `json:"reward_xp"`
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) error {
	_, err := q.db.ExecContext(ctx, createChallenge,
		arg.SessionID,
		arg.PlayerID,
		arg.ChallengeType,
		arg.Title,
		arg.Description,
		arg.TargetParcelID,
		arg.RewardCoins,
		arg.RewardXp,
	)
	return err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (session_id, player_id, message) VALUES (?, ?, ?) RETURNING id, session_id, player_id, message, created_at
`

type CreateChatMessageParams struct {
	SessionID string `json:"session_id"`
	PlayerID  string `json:"player_id"`
	Message   string `json:"message"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage, arg.SessionID, arg.PlayerID, arg.Message)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const createPlayer = `-- name: CreatePlayer :exec
INSERT INTO players (id, name, rejoin_token) VALUES (?, ?, ?)
`

type CreatePlayerParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	RejoinToken string `json:"rejoin_token"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) error {
	_, err := q.db.ExecContext(ctx, createPlayer, arg.ID, arg.Name, arg.RejoinToken)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO game_sessions (id, name, invite_code, municipality_code, municipality_name, center_lon, center_lat, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	InviteCode       string  `json:"invite_code"`
	MunicipalityCode string  `json:"municipality_code"`
	MunicipalityName string  `json:"municipality_name"`
	CenterLon        float64 `json:"center_lon"`
	CenterLat        float64 `json:"center_lat"`
	CreatedBy        string  `json:"created_by"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Name,
		arg.InviteCode,
		arg.MunicipalityCode,
		arg.MunicipalityName,
		arg.CenterLon,
		arg.CenterLat,
		arg.CreatedBy,
	)
	return err
}

const createTreasure = `-- name: CreateTreasure :exec
INSERT INTO treasures (session_id, lon, lat, treasure_type, value) VALUES (?, ?, ?, ?, ?)
`

type CreateTreasureParams struct {
	SessionID    string  `json:"session_id"`
	Lon          float64 `json:"lon"`
	Lat          float64 `json:"lat"`
	TreasureType string  `json:"treasure_type"`
	Value        int64   `json:"value"`
}

func (q *Queries) CreateTreasure(ctx context.Context, arg CreateTreasureParams) error {
	_, err := q.db.ExecContext(ctx, createTreasure,
		arg.SessionID,
		arg.Lon,
		arg.Lat,
		arg.TreasureType,
		arg.Value,
	)
	return err
}

const getCachedData = `-- name: GetCachedData :one
SELECT data FROM api_cache WHERE cache_key = ? AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetCachedData(ctx context.Context, cacheKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCachedData, cacheKey)
	var data string
	err := row.Scan(&data)
	return data, err
}

const getParcelClaim = `-- name: GetParcelClaim :one
SELECT id, session_id, player_id, parcel_id, kg_code, gnr, area_sqm, landuse, converted_to, purchase_price, claimed_at FROM parcel_claims WHERE session_id = ? AND parcel_id = ?
`

type GetParcelClaimParams struct {
	SessionID string `json:"session_id"`
	ParcelID  string `json:"parcel_id"`
}

func (q *Queries) GetParcelClaim(ctx context.Context, arg GetParcelClaimParams) (ParcelClaim, error) {
	row := q.db.QueryRowContext(ctx, getParcelClaim, arg.SessionID, arg.ParcelID)
	var i ParcelClaim
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.ParcelID,
		&i.KgCode,
		&i.Gnr,
		&i.AreaSqm,
		&i.Landuse,
		&i.ConvertedTo,
		&i.PurchasePrice,
		&i.ClaimedAt,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, name, rejoin_token, municipality_code, municipality_name, coins, biodiversity_score, level, xp, created_at, last_seen FROM players WHERE id = ?
`

func (q *Queries) GetPlayerByID(ctx context.Context, id string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RejoinToken,
		&i.MunicipalityCode,
		&i.MunicipalityName,
		&i.Coins,
		&i.BiodiversityScore,
		&i.Level,
		&i.Xp,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getPlayerByName = `-- name: GetPlayerByName :one
SELECT id, name, rejoin_token, municipality_code, municipality_name, coins, biodiversity_score, level, xp, created_at, last_seen FROM players WHERE name = ?
`

func (q *Queries) GetPlayerByName(ctx context.Context, name string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByName, name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RejoinToken,
		&i.MunicipalityCode,
		&i.MunicipalityName,
		&i.Coins,
		&i.BiodiversityScore,
		&i.Level,
		&i.Xp,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getPlayerByToken = `-- name: GetPlayerByToken :one
SELECT id, name, rejoin_token, municipality_code, municipality_name, coins, biodiversity_score, level, xp, created_at, last_seen FROM players WHERE rejoin_token = ?
`

func (q *Queries) GetPlayerByToken(ctx context.Context, rejoinToken string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByToken, rejoinToken)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RejoinToken,
		&i.MunicipalityCode,
		&i.MunicipalityName,
		&i.Coins,
		&i.BiodiversityScore,
		&i.Level,
		&i.Xp,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getPlayerChallenges = `-- name: GetPlayerChallenges :many
SELECT id, session_id, player_id, challenge_type, title, description, target_parcel_id, reward_coins, reward_xp, completed, completed_at, created_at FROM challenges WHERE session_id = ? AND player_id = ? AND completed = 0
`

type GetPlayerChallengesParams struct {
	SessionID string `json:"session_id"`
	PlayerID  string `json:"player_id"`
}

func (q *Queries) GetPlayerChallenges(ctx context.Context, arg GetPlayerChallengesParams) ([]Challenge, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerChallenges, arg.SessionID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Challenge{}
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PlayerID,
			&i.ChallengeType,
			&i.Title,
			&i.Description,
			&i.TargetParcelID,
			&i.RewardCoins,
			&i.RewardXp,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerParcels = `-- name: GetPlayerParcels :many
SELECT id, session_id, player_id, parcel_id, kg_code, gnr, area_sqm, landuse, converted_to, purchase_price, claimed_at FROM parcel_claims WHERE session_id = ? AND player_id = ?
`

type GetPlayerParcelsParams struct {
	SessionID string `json:"session_id"`
	PlayerID  string `json:"player_id"`
}

func (q *Queries) GetPlayerParcels(ctx context.Context, arg GetPlayerParcelsParams) ([]ParcelClaim, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerParcels, arg.SessionID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParcelClaim{}
	for rows.Next() {
		var i ParcelClaim
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PlayerID,
			&i.ParcelID,
			&i.KgCode,
			&i.Gnr,
			&i.AreaSqm,
			&i.Landuse,
			&i.ConvertedTo,
			&i.PurchasePrice,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerSessions = `-- name: GetPlayerSessions :many
SELECT gs.id, gs.name, gs.invite_code, gs.municipality_code, gs.municipality_name, gs.center_lon, gs.center_lat, gs.created_by, gs.created_at, gs.status FROM game_sessions gs
JOIN session_players sp ON sp.session_id = gs.id
WHERE sp.player_id = ? AND gs.status = 'active'
`

func (q *Queries) GetPlayerSessions(ctx context.Context, playerID string) ([]GameSession, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerSessions, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameSession{}
	for rows.Next() {
		var i GameSession
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.MunicipalityCode,
			&i.MunicipalityName,
			&i.CenterLon,
			&i.CenterLat,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentChat = `-- name: GetRecentChat :many
SELECT cm.id, cm.session_id, cm.player_id, cm.message, cm.created_at, p.name as player_name FROM chat_messages cm
JOIN players p ON p.id = cm.player_id
WHERE cm.session_id = ?
ORDER BY cm.created_at DESC LIMIT ?
`

type GetRecentChatParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

type GetRecentChatRow struct {
	ID         int64     `json:"id"`
	SessionID  string    `json:"session_id"`
	PlayerID   string    `json:"player_id"`
	Message    string    `json:"message"`
	CreatedAt  time.Time `json:"created_at"`
	PlayerName string    `json:"player_name"`
}

func (q *Queries) GetRecentChat(ctx context.Context, arg GetRecentChatParams) ([]GetRecentChatRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentChat, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentChatRow{}
	for rows.Next() {
		var i GetRecentChatRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PlayerID,
			&i.Message,
			&i.CreatedAt,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, name, invite_code, municipality_code, municipality_name, center_lon, center_lat, created_by, created_at, status FROM game_sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (GameSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.MunicipalityCode,
		&i.MunicipalityName,
		&i.CenterLon,
		&i.CenterLat,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getSessionBiodiversityPercent = `-- name: GetSessionBiodiversityPercent :one
SELECT
    COALESCE(SUM(CASE WHEN converted_to = 'biodiversity' THEN area_sqm ELSE 0 END), 0) as bio_area,
    COALESCE(SUM(area_sqm), 0) as total_area
FROM parcel_claims WHERE session_id = ?
`

type GetSessionBiodiversityPercentRow struct {
	BioArea   interface{} `json:"bio_area"`
	TotalArea interface{} `json:"total_area"`
}

func (q *Queries) GetSessionBiodiversityPercent(ctx context.Context, sessionID string) (GetSessionBiodiversityPercentRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionBiodiversityPercent, sessionID)
	var i GetSessionBiodiversityPercentRow
	err := row.Scan(&i.BioArea, &i.TotalArea)
	return i, err
}

const getSessionByInvite = `-- name: GetSessionByInvite :one
SELECT id, name, invite_code, municipality_code, municipality_name, center_lon, center_lat, created_by, created_at, status FROM game_sessions WHERE invite_code = ?
`

func (q *Queries) GetSessionByInvite(ctx context.Context, inviteCode string) (GameSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByInvite, inviteCode)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.MunicipalityCode,
		&i.MunicipalityName,
		&i.CenterLon,
		&i.CenterLat,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getSessionParcels = `-- name: GetSessionParcels :many
SELECT id, session_id, player_id, parcel_id, kg_code, gnr, area_sqm, landuse, converted_to, purchase_price, claimed_at FROM parcel_claims WHERE session_id = ?
`

func (q *Queries) GetSessionParcels(ctx context.Context, sessionID string) ([]ParcelClaim, error) {
	rows, err := q.db.QueryContext(ctx, getSessionParcels, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParcelClaim{}
	for rows.Next() {
		var i ParcelClaim
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PlayerID,
			&i.ParcelID,
			&i.KgCode,
			&i.Gnr,
			&i.AreaSqm,
			&i.Landuse,
			&i.ConvertedTo,
			&i.PurchasePrice,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionPlayers = `-- name: GetSessionPlayers :many
SELECT p.id, p.name, p.rejoin_token, p.municipality_code, p.municipality_name, p.coins, p.biodiversity_score, p.level, p.xp, p.created_at, p.last_seen FROM players p
JOIN session_players sp ON sp.player_id = p.id
WHERE sp.session_id = ?
`

func (q *Queries) GetSessionPlayers(ctx context.Context, sessionID string) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getSessionPlayers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RejoinToken,
			&i.MunicipalityCode,
			&i.MunicipalityName,
			&i.Coins,
			&i.BiodiversityScore,
			&i.Level,
			&i.Xp,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionTreasures = `-- name: GetSessionTreasures :many
SELECT id, session_id, lon, lat, treasure_type, value, found_by, found_at, created_at FROM treasures WHERE session_id = ? AND found_by IS NULL
`

func (q *Queries) GetSessionTreasures(ctx context.Context, sessionID string) ([]Treasure, error) {
	rows, err := q.db.QueryContext(ctx, getSessionTreasures, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Treasure{}
	for rows.Next() {
		var i Treasure
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Lon,
			&i.Lat,
			&i.TreasureType,
			&i.Value,
			&i.FoundBy,
			&i.FoundAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinSession = `-- name: JoinSession :exec
INSERT OR IGNORE INTO session_players (session_id, player_id) VALUES (?, ?)
`

type JoinSessionParams struct {
	SessionID string `json:"session_id"`
	PlayerID  string `json:"player_id"`
}

func (q *Queries) JoinSession(ctx context.Context, arg JoinSessionParams) error {
	_, err := q.db.ExecContext(ctx, joinSession, arg.SessionID, arg.PlayerID)
	return err
}

const setCachedData = `-- name: SetCachedData :exec
INSERT OR REPLACE INTO api_cache (cache_key, data, fetched_at, expires_at)
VALUES (?, ?, CURRENT_TIMESTAMP, ?)
`

type SetCachedDataParams struct {
	CacheKey  string    `json:"cache_key"`
	Data      string    `json:"data"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) SetCachedData(ctx context.Context, arg SetCachedDataParams) error {
	_, err := q.db.ExecContext(ctx, setCachedData, arg.CacheKey, arg.Data, arg.ExpiresAt)
	return err
}

const updatePlayerBiodiversity = `-- name: UpdatePlayerBiodiversity :exec
UPDATE players SET biodiversity_score = ?, last_seen = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdatePlayerBiodiversityParams struct {
	BiodiversityScore float64 `json:"biodiversity_score"`
	ID                string  `json:"id"`
}

func (q *Queries) UpdatePlayerBiodiversity(ctx context.Context, arg UpdatePlayerBiodiversityParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerBiodiversity, arg.BiodiversityScore, arg.ID)
	return err
}

const updatePlayerCoins = `-- name: UpdatePlayerCoins :exec
UPDATE players SET coins = coins + ?, last_seen = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdatePlayerCoinsParams struct {
	Coins int64  `json:"coins"`
	ID    string `json:"id"`
}

func (q *Queries) UpdatePlayerCoins(ctx context.Context, arg UpdatePlayerCoinsParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerCoins, arg.Coins, arg.ID)
	return err
}

const updatePlayerLevel = `-- name: UpdatePlayerLevel :exec
UPDATE players SET level = ?, last_seen = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdatePlayerLevelParams struct {
	Level int64  `json:"level"`
	ID    string `json:"id"`
}

func (q *Queries) UpdatePlayerLevel(ctx context.Context, arg UpdatePlayerLevelParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerLevel, arg.Level, arg.ID)
	return err
}

const updatePlayerMunicipality = `-- name: UpdatePlayerMunicipality :exec
UPDATE players SET municipality_code = ?, municipality_name = ?, last_seen = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdatePlayerMunicipalityParams struct {
	MunicipalityCode *string `json:"municipality_code"`
	MunicipalityName *string `json:"municipality_name"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdatePlayerMunicipality(ctx context.Context, arg UpdatePlayerMunicipalityParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerMunicipality, arg.MunicipalityCode, arg.MunicipalityName, arg.ID)
	return err
}

const updatePlayerXP = `-- name: UpdatePlayerXP :exec
UPDATE players SET xp = xp + ?, last_seen = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdatePlayerXPParams struct {
	Xp int64  `json:"xp"`
	ID string `json:"id"`
}

func (q *Queries) UpdatePlayerXP(ctx context.Context, arg UpdatePlayerXPParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerXP, arg.Xp, arg.ID)
	return err
}
