// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type ApiCache struct {
	CacheKey  string    `json:"cache_key"`
	Data      string    `json:"data"`
	FetchedAt time.Time `json:"fetched_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Challenge struct {
	ID             int64      `json:"id"`
	SessionID      string     `json:"session_id"`
	PlayerID       string     `json:"player_id"`
	ChallengeType  string     `json:"challenge_type"`
	Title          string     `json:"title"`
	Description    *string    `json:"description"`
	TargetParcelID *string    `json:"target_parcel_id"`
	RewardCoins    int64      `json:"reward_coins"`
	RewardXp       int64      `json:"reward_xp"`
	Completed      int64      `json:"completed"`
	CompletedAt    *time.Time `json:"completed_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type ChatMessage struct {
	ID        int64     `json:"id"`
	SessionID string    `json:"session_id"`
	PlayerID  string    `json:"player_id"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
	Hidden    int64     `json:"hidden"`
	Flag      string    `json:"flag"`
}

type GameSession struct {
	ID               string    `json:"id"`
	Name             string    `json:"name"`
	InviteCode       string    `json:"invite_code"`
	MunicipalityCode string    `json:"municipality_code"`
	MunicipalityName string    `json:"municipality_name"`
	CenterLon        float64   `json:"center_lon"`
	CenterLat        float64   `json:"center_lat"`
	CreatedBy        string    `json:"created_by"`
	CreatedAt        time.Time `json:"created_at"`
	Status           string    `json:"status"`
	ChatMode         string    `json:"chat_mode"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type ParcelClaim struct {
	ID            int64     `json:"id"`
	SessionID     string    `json:"session_id"`
	PlayerID      string    `json:"player_id"`
	ParcelID      string    `json:"parcel_id"`
	KgCode        string    `json:"kg_code"`
	Gnr           string    `json:"gnr"`
	AreaSqm       float64   `json:"area_sqm"`
	Landuse       *string   `json:"landuse"`
	ConvertedTo   *string   `json:"converted_to"`
	PurchasePrice int64     `json:"purchase_price"`
	ClaimedAt     time.Time `json:"claimed_at"`
	Ez            string    `json:"ez"`
}

type ParcelOffer struct {
	ID         int64      `json:"id"`
	SessionID  string     `json:"session_id"`
	ParcelID   string     `json:"parcel_id"`
	ClaimID    int64      `json:"claim_id"`
	BuyerID    string     `json:"buyer_id"`
	SellerID   string     `json:"seller_id"`
	OfferPrice int64      `json:"offer_price"`
	Status     string     `json:"status"`
	CreatedAt  *time.Time `json:"created_at"`
	ResolvedAt *time.Time `json:"resolved_at"`
}

type Player struct {
	ID                string     `json:"id"`
	Name              string     `json:"name"`
	RejoinToken       string     `json:"-"`
	MunicipalityCode  *string    `json:"municipality_code"`
	MunicipalityName  *string    `json:"municipality_name"`
	Coins             int64      `json:"coins"`
	BiodiversityScore float64    `json:"biodiversity_score"`
	Level             int64      `json:"level"`
	Xp                int64      `json:"xp"`
	CreatedAt         time.Time  `json:"created_at"`
	LastSeen          time.Time  `json:"last_seen"`
	ChatStrikes       int64      `json:"-"`
	ChatMutedUntil    *time.Time `json:"-"`
	ChatBanned        int64      `json:"-"`
	ChatRulesAccepted int64      `json:"chat_rules_accepted"`
}

type PlayerBlock struct {
	PlayerID  string    `json:"player_id"`
	BlockedID string    `json:"blocked_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Report struct {
	ID               int64     `json:"id"`
	SessionID        string    `json:"session_id"`
	MessageID        *int64    `json:"message_id"`
	ReportedPlayerID string    `json:"reported_player_id"`
	ReporterID       string    `json:"reporter_id"`
	Reason           string    `json:"reason"`
	Note             string    `json:"note"`
	Action           string    `json:"action"`
	CreatedAt        time.Time `json:"created_at"`
}

type SafetyEvent struct {
	ID        int64     `json:"id"`
	Kind      string    `json:"kind"`
	PlayerID  *string   `json:"player_id"`
	SessionID *string   `json:"session_id"`
	Detail    string    `json:"detail"`
	CreatedAt time.Time `json:"created_at"`
}

type SessionPlayer struct {
	SessionID string    `json:"session_id"`
	PlayerID  string    `json:"player_id"`
	JoinedAt  time.Time `json:"joined_at"`
}

type Treasure struct {
	ID              int64      `json:"id"`
	SessionID       string     `json:"session_id"`
	Lon             float64    `json:"lon"`
	Lat             float64    `json:"lat"`
	TreasureType    string     `json:"treasure_type"`
	Value           int64      `json:"value"`
	FoundBy         *string    `json:"found_by"`
	FoundAt         *time.Time `json:"found_at"`
	CreatedAt       time.Time  `json:"created_at"`
	SpeciesName     string     `json:"species_name"`
	SpeciesGerman   string     `json:"species_german"`
	SpeciesCategory string     `json:"species_category"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
